# config/settings.py

# Stock tickers to analyze
NIFTY_TICKERS = ['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS']

# Data fetching parameters
DATA_PERIOD = "7mo"  # Fetch 7 months to ensure enough data for 6mo backtest + indicators
DATA_INTERVAL = "1d"

# Google Sheets configuration
GOOGLE_SHEET_NAME = "stock_market"
CREDENTIALS_FILE = "config/creds.json"

# Strategy parameters
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
SMA_SHORT = 20
SMA_LONG = 50


NIFTY_50_STOCKS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS',
    'HINDUNILVR.NS', 'BHARTIARTL.NS', 'ITC.NS', 'SBIN.NS', 'LICI.NS',
    'KOTAKBANK.NS', 'HCLTECH.NS', 'LT.NS', 'AXISBANK.NS', 'BAJFINANCE.NS',
    'MARUTI.NS', 'SUNPHARMA.NS', 'ASIANPAINT.NS', 'ADANIENT.NS', 'TITAN.NS',
    'ULTRACEMCO.NS', 'WIPRO.NS', 'NESTLEIND.NS', 'ONGC.NS', 'NTPC.NS',
    'JSWSTEEL.NS', 'M&M.NS', 'ADANIPORTS.NS', 'POWERGRID.NS', 'COALINDIA.NS',
    'SBILIFE.NS', 'BAJAJFINSV.NS', 'HDFCLIFE.NS', 'EICHERMOT.NS', 'GRASIM.NS',
    'HINDALCO.NS', 'INDUSINDBK.NS', 'BRITANNIA.NS', 'CIPLA.NS', 'DRREDDY.NS',
    'TECHM.NS', 'APOLLOHOSP.NS', 'UPL.NS', 'HEROMOTOCO.NS', 'DIVISLAB.NS',
    'SHRIRAMFIN.NS', 'BPCL.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'BAJAJ-AUTO.NS'
]